export const criticaMajorVal = [
  '<b>ESCENA CADAFAL. INTRODUCCIÓ.</b><br>Entre onades de paraula buida<br>s\'alcen vaixells de fum i mentida;<br>el poble rema, cec i cansat,<br>buscant la riba que mai ha arribat.',
  'A la costa, els de sempre prometen<br>"una Gandia millor que ahir",<br>però entre fotos i projectes<br>tot torna al mateix color gris.',
  'Sota la ciutat, la mar ja no creu.<br>Tritó alça el braç, convoca l\'onada,<br>però el seu crit s\'apaga en l\'albada<br>i el poble afonat diu: "Això és el que es veu".',
  'Tritó denuncia un port sense rumb,<br>ple de decrets, maniobres i runa;<br>ombres que dansen sota la lluna<br>i acords que pesen com plom al fons.',
  'La sirena riu per davall l\'aigua,<br>com qui ja sap com acabarà:<br>Afonats esteu, i encara voleu<br>més mar per tornar a negociar?',
  'Diuen: "Ho tenim controlat",<br>com quan plou fort a Germanies;<br>però l\'aigua desmenteix el relat<br>i el mar s\'emporta les fantasies.',
  'El mariner busca glòria,<br>com qui promet canvis al cantó;<br>però el serpis li conta la història:<br>qui no treballa no troba flor.',
  'Al final, tant pirata com or<br>són faules d\'un món ja cansat;<br>i Gandia, que coneix el mercat,<br>sap triar millor el seu propi port.',
  '<b>1. Capità de les Falles d\'especial.</b><br>El “capità” porta el timó,<br>veu la festa com empresa;<br>cada acte és nova peça,<br>per fer caixa al pantaló.',
  'El nou “Florentino” ha arribat,<br>des de Vila Nova mana;<br>organitza, suma i trama,<br>amb balanç ben calculat.',
  'Prado aguanta la posició,<br>no vol perdre categoria;<br>si el cens no quadra, ja s\'arregla,<br>mentre salven distinció.',
  'Màrtirs vol deixar empremta,<br>han tirat la casa fora;<br>monument que tot ho devora,<br>per fer història que vença.',
  'Mercat arriba nou,<br>vol parlar amb la infantil,<br>i encara que siga humil,<br>sap fer-se sentir prou.',
  'Vila Nova ja és Port Nou,<br>com si fóra el mateix grau;<br>on abans hi havia pau,<br>ara tot es mou pel “sou”.',
  'L\'ajuntament diu sí,<br>si Gandia guanya fama,<br>mentre la Junta es reclama,<br>perdent rumb des d\'ací.',
  'I el capità veu clar,<br>que la festa és mercat,<br>tot signat i visat,<br>mentre torne a sumar.',
  '<b>2. Tonell 1. Titulats manipulats.</b><br>Dins del mar del nostre monument<br>suren barrils que ningú reclama;<br>porten verí, porten drama,<br>i un “jo no he sigut” permanent.',
  'A Gandia el verí té banda sonora:<br>rumor, crispació i veu interessada;<br>tertúlia encesa, veritat fragmentada,<br>i silenci còmplice que tot ho decora.',
  'Radio Gandia dona el titular,<br>Onda Naranja el debat radiant.<br>I mentre, el verí puja, lent i constant,<br>les ones parlen des del seu canal:',
  'Comarcal TV pinta postal,<br>Radio Marca encén la conversa;<br>molt de soroll, poca reversa,<br>i el fons continua més abismal.',
  'Tertúlies on tres parlen i huit criden,<br>emissores que canvien el relat;<br>segons qui entra, tot queda oblidat,<br>i els barrils, mentre, més pes adquireixen.',
  'També hi ha meduses divines<br>flotant per la informació,<br>que piquen amb formes fines<br>quan repeteixen la lliçó.',
  'Si una mentida es repeteix<br>mil vegades pel canal,<br>acaba semblant notícia…<br>per molt que siga banal.',
  'Però el poble, vell pescador,<br>ja coneix bé este oceà:<br>quan el soroll és massa gran<br>algú t\'està marejant.',
  '<b>3. Tonell 2.</b><br>De Gandia cap a València<br>ix un vaixell molt singular,<br>diuen que és tren de rodalies<br>però costa de trobar.',
  'Un dia ix, l\'altre descansa,<br>l\'altre arriba tard al port,<br>i el passatger mira el rellotge<br>mentre perd mig matí mort.',
  'Entre avaries i retards<br>la gent ja té tradició:<br>portar avituallament<br>i encomanar-se al patró.',
  'Quan el tren torna a fallar<br>ningú dona explicacions<br>els passatgers com sardines<br>s\'apreten en els vagons.',
  'Canvien els governs<br>i sense cap importuni<br>cap d\'ells es posa a acabar<br>el corredor mediterrani.',
  'El poble, que es viatger,<br>ja diu amb resignació:<br>si vols arribar a València…<br>ix de casa abans del sol.',
  '<b>4. Ecològica – Barco 50 aniversari.</b><br>Mig segle lluitant contra vents i marees,<br>fent de cada colp una lliçó que ens crea,<br>i de cada naufragi un nou despertar,<br>amb una flama tossuda que mai vol callar.',
  'Cinquanta hiverns fent força a la tempesta,<br>cridant al món que ací la flama és fer festa,<br>i que persistir és l\'ofici heretat,<br>d\'una falla que no s\'ha rendit mai.',
  'Ara mirem arrere amb ulls tranquils,<br>sabent que els errors ens feren més hàbils;<br>mig segle de caure i tornar a plantar,<br>d\'afonar-nos junts... i junts tornar a alçar.',
  'I ací estem, orgullosos, en mar serena,<br>mirant el futur sense cap cadena.<br>Si la història ens ha fet navegar així,<br>cincanta anys més... i que siga ací.',
  '<b>5. Sirenes - oposició.</b><br>Com cantes les belles sirenes<br>canta a Gandia l\'oposició.<br>Tot ho veuen ben negre,<br>però no proposen solució.',
  'Per fer el vídeo més viral<br>la batalla els polítics fan.<br>Soler com si fora reporter de fama,<br>crea una Gandia, tota plena de drama.',
  'Millet i el seu càmera café,<br>sembla Vox una paròdia.<br>Però ho fa amb consciència<br>negre ho tindrem si governa.',
  'El PP va destapant les vergonyes.<br>El xec consum, diu, és un frau<br>amb descàrrega de dades<br>sense demanar si us plau.',
  'Diuen que oberta la porta estava<br>en el padró municipal.<br>Que ha estat la màniga ampla<br>i la ciutat s\'ha fet ben gran.',
  'I mentre critiquen i critiquen<br>pensen ja en eleccions.<br>Bona cara ens fiquen,<br>per arrapar-nos els vots.',
  'Mes tant se val el partit<br>l\'únic que volen és guanyar.<br>Però la gent ja ara filem prim<br>ja no ens poden enganyar.',
  'Amb Mazón dins encara<br>poc farà Soler i quadrilla.<br>Que ací no oblidem la Dana<br>ni que Sánchez no envià ajuda.',
  '<b>6. LGTBI.</b><br>Estimar no és un delicte<br>ni motiu de condemna,<br>l\'homofòbia sí que és<br>la vergonya eterna.',
  'La igualtat no resta<br>suma cors<br>i el món serà just<br>quan respectem tots els amors.',
  'Som qui som<br>sense demanar perdó<br>orgull al carrer<br>amor sense por.',
  'No demanem privilegis<br>ni llocs superiors<br>només drets compartits<br>i carrers sense por.',
  'El moviment LGTBI+<br>no és moda ni reclam<br>és un dret a viure lliure<br>sense por ni amagar.',
  'Cap insult apagarà la llum<br>d\'un amor sincer,<br>contra l\'homofòbia<br>respecte per a voler.',
  '<b>7. Escena del nàufrag Francisco en l\'illa deserta.</b><br>Francisco el conqueridor<br>que venia a modernitzar<br>i els actes remodelar<br>ja s\'ha quedat encallat.',
  'En la seua illa deserta<br>es troba poc recolzat<br>i ja flaquegen les forces<br>per a dur-ho tot endavant.',
  'Per això el sr. Francisco<br>al Foc i Flama s\'ha entronitzat<br>que la seua veu retrone<br>del Grau a Benipeixcar.',
  'Un Foc i Flama amb dues versions<br>tot una innovació<br>trïa la foto que vullgues<br>per a la següent edició.',
  'Mal canvi de retratista<br>acostumat a l\'artista<br>s\'ha pensat que este llibre<br>és com una revista.',
  'Bé li vindrà a Joaquin Lerma<br>per pagar la trencà del pont<br>ja que el Foc i Flama enguany<br>el reciclarà tot el món.',
  'A Telmo ha fet bó<br>i millor a l\'anterior<br>vorem el que queda<br>que encara pot ser pitjor.',
  '<b>8. Tauró: especulador. Glamping de Gandia.</b><br>Del blau profund ix el tauró sigil·lós,<br>mira Gandia com qui mira un banquet;<br>on veu un solar ja imagina el xec,<br>i el poble tremola davant del seu mos.',
  'Alguns el confonen amb fera animal,<br>però el perill real porta americana;<br>signa convenis amb mà molt humana<br>i deixa el barri més car que el coral.',
  'Projectes que duren més que un temporal,<br>licitacions que tornen i tornen;<br>promeses que, quan més s\'adornen,<br>fan gust d\'escata electoral.',
  'El glamping promet un paradís postal,<br>ven fum verd embolicat de sagí,<br>però aixafa granotes i aus d\'ací,<br>i fa del silenci un crim ambiental.',
  'Diu l\'alcalde: “és progrés sostenible”,<br>mentre el tauró ja firma davant notari,<br>porta el projecte fet, el benefici clar i diari,<br>i l\'ullal tremola, fràgil i invisible.',
  'Naden fi, com si res passara,<br>com si el preu no caiguera damunt;<br>i el mar murmura, constant i profund:<br>“el pitjor mos és el que no es declara”.',
  '<b>9. Barril amb pardal pirata.</b><br>Com qui vol alçar-se sense tocar fang,<br>hi trobem l\'alcalde de vol mesurat;<br>parla fi, amb to calmat i moderat,<br>mentre el barril continua ple i pesant.',
  'Damunt del bidó rovellat i callat,<br>fa equilibris amb prudència i trellat;<br>sap que baixar té un preu elevat,<br>i dalt el pes sempre sembla alleujat.',
  'En este mar de contractes<br>navegava un gran patró:<br>Ábalos el secretari<br>portant l\'organització.',
  'Diu que ell sols feia ruta<br>pel port institucional,<br>però el vaixell feia escala<br>on la caixa era especial.',
  'Pel vaixell corre Koldo<br>un cranc molt espavilat,<br>pujant bosses i maletins<br>del moll fins al reservat.',
  'Cerdán diu que fa el viatge<br>per servir a la nació,<br>mentre va estenent la xarxa<br>per a pescar comissions.',
  'Però el poble, que és mariner,<br>ja coneix bé la cançó:<br>quan hi ha tanta txistorreta…<br>algú paga el peroló.',
  'Perquè governar no és sols evitar el fang,<br>ni volar damunt del conflicte present;<br>és baixar, assumir el pes del moment,<br>i evitar que el verí ens acabe afonant.',
  'I així, damunt del barril encara ple,<br>el pardal manté el rumb i la postura;<br>però el mar murmura amb veu madura:<br>“Governar bé també és baixar i fer”.'
];
