export const criticaMajorEu = [
  '<b>ATAUTZ‑ESZENA. SARRERA.</b><br>Hitz hutsen olatuen artean<br>kea eta gezurra dira itsasontziak;<br>herria arraunean doa, itsu eta nekaturik,<br>inoiz iritsi ez den itsasertza bilatuz.',
  'Kostaldean, betikoek agintzen dute<br>"atzo baino Gandia hobea",<br>baina argazki eta proiektuen artean<br>dena itzultzen da gris bera izatera.',
  'Hiriaren azpian, itsasoak jada ez du sinesten.<br>Tritoiak besoak altxatzen ditu, olatua deitzen;<br>baina bere oihua egunsentian itzaltzen da<br>eta hondoratuta dagoen herriak dio: "Hau da ikusten dena".',
  'Tritoiek norabiderik gabeko portua salatzen du,<br>dekretu, maniobra eta hondakinez betea;<br>ilargipean dantzatzen duten itzalak<br>eta behe‑hondora berun astun gisa jausten diren akordioak.',
  'Sereak barre egiten du uretatik behera,<br>badakienak bezala nola bukatuko den:<br>"Hondoratuta zaudete, eta hala ere nahi duzue<br>itsaso gehiago berriro negoziatzeko?".',
  'Esaten dute: "dena kontrolpean dugu",<br>Germanies kalean gogor euria egiten duenean bezala;<br>baina urak gezurtatzen du kontakizuna<br>eta itsasoak fantasiak eramaten ditu.',
  'Itsasgizona ospearen atzetik doa,<br>kantoian aldaketak agintzen dituen bezalaxe;<br>baina sugeak istorioa kontatzen dio:<br>lanik egiten ez duenak ez du lorerik aurkitzen.',
  'Azken batean, bai piratak bai urrea<br>nekatutako mundu baten ipuin zaharrak dira;<br>eta merkatua ondo ezagutzen duen Gandiak<br>hobeto aukeratzen du bere portu propioa.',
  '<b>1. Berezi‑ataleko Fallasetako kapitaina.</b><br>"Kapitainak" lemazaina darama,<br>festa enpresa moduan ikusten du;<br>ekitaldi bakoitza pieza berria da<br>diru‑kutxa betetzen jarraitzeko.',
  '"Florentino" berria iritsi da,<br>Vila Novatik agintzen du;<br>antolatu, batu eta konspiratu egiten du,<br>ondo neurtutako balantzearekin.',
  'Pradok posizioa eusten du,<br>ez du kategoria galdu nahi;<br>errolda ez badator bat, konpondu egingo dute,<br>distantzia salbatuz, berehala.',
  'Mártires kaleak aztarna utzi nahi du,<br>etxea leihotik bota dute;<br>dena irensten duen monumentua<br>irabazlea izango den historia idazteko.',
  'Mercat auzoa berria da,<br>haurren fallarekin hitz egin nahi du;<br>eta xumeagoa dirudien arren,<br>ondo jakin du bere ahotsa altxatzen.',
  'Vila Nova orain Port Nou da,<br>maila bera izango balitz bezala;<br>lehen bakea nagusi zen lekuan,<br>orain dena "sou"arengatik mugitzen da.',
  'Udalak "bai" esaten du<br>Gandiak ospea irabazten badu;<br>bitartean Batzordea kexu dabil,<br>norabidea galduta dagoenetik.',
  'Eta kapitainak argi ikusten du:<br>festa merkatua dela soilik;<br>dena sinatuta eta zigortuta,<br>berriro zenbatzen duen bitartean.',
  '<b>2. Upela 1. Tituludun manipulatuak.</b><br>Gure monumentuaren itsasoan barrena<br>inork aldarrikatzen ez dituen upelak flotatzen dira;<br>pozoiak eta dramak daramatzate,<br>eta etengabeko "nik ez dut izan" hotsa.',
  'Gandian pozoiak soinu banda du:<br>zurrumurruak, tentsioa eta ahots interesatuak;<br>tertulia sutsuak, egia zatitua,<br>eta dena estaltzen duen isiltasun konplizea.',
  'Radio Gandiak titularra ematen du,<br>Onda Naranjak eztabaida pizten du;<br>eta bitartean, pozoiak gora egiten du, poliki baina etengabe,<br>uhinek beren kanaletik hitz egiten duten bitartean:',
  'Comarcal TBk postalak margotzen ditu,<br>Radio Marcak solasaldia pizten du;<br>zarata asko, ia batere atzera egin gabe,<br>eta hondoak gero eta amildegi handiagoa dirudi.',
  'Tertulietan hiru hizketan eta zortzi oihuka,<br>istorioa aldatzen duten irratiak;<br>nor sartzen den, hala ahazten dira egitateak,<br>eta, bitartean, upeleek gero eta pisu handiagoa dute.',
  'Baita medusa "jainkotuak" ere badaude<br>informazioaren gainean flotatzen;<br>ukitu dotorez ziztatzen dute<br>ikasgaia mila aldiz errepikatzean.',
  'Gezur bat behin eta berriz errepikatzen bada<br>mila aldiz kate berean,<br>azkenean albiste dirudie<br>nahiz eta hutsala izan muinean.',
  'Baina herriak, arrantzale zaharrak,<br>itsaso hau ondo ezagutzen du jada;<br>zarata gehiegi dagoenean<br>norbaitek burua ematen dizu bueltaka.',
  '<b>3. Upela 2.</b><br>Gandiatik Valenciarako bidean<br>itsasontzi berezi bat irteten da;<br>diote aldirietako trena dela,<br>baina zaila da inoiz aurkitzea.',
  'Egun batean ateratzen da, hurrengoan atseden,<br>beste batean portura berandu iristen da;<br>eta bidaiariak erlojua begiratzen du<br>goiz erdia galduta doan bitartean.',
  'Matxuren eta atzerapenen artean<br>ohitura bihurtu da jada:<br>janaria eta edaria eramatea<br>eta patroia otoitzetan gogoratzea.',
  'Trena berriro huts egiten duenean<br>inork ez du azalpenik ematen;<br>eta bidaiariak sardina ontzi baten moduan<br>beste behin torlojututa doaz bagoietan.',
  'Gobernuak aldatzen dira,<br>kolorea gorri edo urdin izan;<br>baina inork ez du serio hartzen<br>Mediterraneoko korridorea amaitzeko lan.',
  'Herria, bidaiaria dena,<br>aspertuta esaten hasi da:<br>"Valenciaraino iritsi nahi baduzu…<br>irtan etxetik eguzkia atera aurretik, bada".',
  '<b>4. Ekologikoa – 50. urteurreneko ontzia.</b><br>Hogei eta hamar urte gehi bost, itsaso eta haizeen aurka,<br>kolpe bakoitza ikasgai bihurtuz;<br>naufragio bakoitza esnatze berria da,<br>inoiz isildu nahi ez duen sugar burugogor batekin.',
  'Berrogeita hamar negu ekaitzari aurre eginez,<br>munduarentzat oihukatuz hemen flama festa dela;<br>eta irautea dela gure lanbide zaharra,<br>inoiz makurtu ez den falla baten herentzia.',
  'Orain atzera begiratzen dugu begi lasaiekin,<br>hutsek trebeago egin gaituztela jakinda;<br>erortzen eta berriz plantatzen eman dugu bizitza,<br>elkarrekin hondoratu eta elkarrekin altxatzen berriro.',
  'Eta hemen gaude, harro, itsaso barean,<br>etorkizunari kateik gabe begira.<br>Historiak horrela nabigatzen irakatsi badigu,<br>beste berrogeita hamar urte gehiago… eta hemen izan daitezela.',
  '<b>5. Sirenak – Oposizioa.</b><br>Sirenaren kanta ederrak bezala<br>horrela abesten du oposizioak Gandian;<br>dena beltz eta beltz ikusten dute,<br>baina ez dute irtenbiderik ekartzen.',
  'Bideoa ahalik eta biralena izan dadin<br>politikariek borroka sareetan egiten dute;<br>Soler, kazetari ospetsua balitz bezala,<br>dramaz betetako Gandia bat margotzen.',
  'Millet eta bere "cámara café"<br>Voxeko parodia dirudi benetan;<br>baina badaki zer egiten duen,<br>berak aginduz gero beltz ikusiko dugulako etorkizuna.',
  'PPk lotsak destapatzen jarraitzen du.<br>"Txekea‑kontsumoa" iruzur dela dio,<br>datu guztiak deskargatuz<br>"mesedez" ere eskatu gabe, horrela.',
  'Esaten dute atea zabalik zegoela<br>udal erroldan bertan;<br>manga zabal‑zabal ibili dela<br>eta hiria handitu egin dela bat‑batean.',
  'Eta kritikatu eta kritikatu bitartean<br>dagoeneko pentsatzen dute hauteskundeetan;<br>aurpegi onak jartzen dizkigute orain<br>gure botoak kentzeko ahaleginean.',
  'Alderdiak gutxi axola du,<br>helburu bakarra irabaztea da;<br>baina herriak orain hari finagoz josten du,<br>eta ezin gaituzte berriz engainatu.',
  'Mazón barruan dagoen honetan ere<br>Soler eta bere kuadrillak gutxi egingo du;<br>hemen ez dugu ahazten Danaren arrastoa<br>ezta Sánchez‑ek bidali ez zuen laguntza ere.',
  '<b>6. LGTBI.</b><br>Maitatzea ez da delitua,<br>ez eta kondenarako arrazoia ere;<br>homofobia bai dela<br>betiko lotsaren iturria.',
  'Berdintasunak ez du kentzen,<br>bihotzak gehitu egiten ditu;<br>eta mundua bidezkoa izango da<br>maitasun guztiak errespetatzen ditugunean.',
  'Gara garenak,<br>barkamena eskatu gabe;<br>harrotasuna kalean,<br>eta beldurrik gabeko maitasuna.',
  'Ez dugu pribilegiorik eskatzen,<br>ez toki gorenen beharrik;<br>partekatutako eskubideak baizik<br>eta beldurrik gabeko kaleak.',
  'LGTBI+ mugimendua<br>ez da moda bat, ezta iragarkia ere;<br>askatasunean bizitzeko eskubidea da,<br>ezkutatu beharrik gabe, beldurrik gabe.',
  'Inongo irainak ezin izango du itzali<br>maitasun zintzo baten argia;<br>homofobiaren aurrean<br>errespetua da gure erantzuna.',
  '<b>7. Francisco naufragoaren eszena uharte huts batean.</b><br>Francisco, konkistatzaile handia,<br>ekitaldiak modernizatzera zetorrena,<br>agendak berrasmatzera eta aldatzera,<br>orain erabat trabatuta geratu da.',
  'Bere uharte huts eta isolatuan<br>euskarririk ia ez du aurkitzen;<br>indarrak agortzen hasi zaizkio dagoeneko<br>dena aurrera eramateko ahaleginean.',
  'Horregatik, jaun Francisco<br>Foc i Flama aldizkarian tronuratuta dago;<br>bere ahotsa oihartzun bihurtu dadin<br>Grau‑tik Benipeixcar‑raino.',
  'Bi bertsio dituen Foc i Flama bat,<br>benetako berrikuntza bat omen;<br>hurrengo ediziorako<br>nahi duzun argazkia aukeratu dezakezu.',
  'Argazkilari aldaketa txarra,<br>artista onetara ohituta;<br>liburu hau aldizkari arin bat<br>zela pentsatu du, antza.',
  'Ongi etorriko zaio Joaquín Lermari<br>zubitik egindako zuloa ordaintzeko;<br>aurten Foc i Flama honek<br>mundu guztiak berrerabiliko duelako.',
  'Telmori ongi atera zaio,<br>aurrekoari baino hobe;<br>ikusi beharko dugu zer geratzen den,<br>oraindik okerragoa izan baitaiteke.',
  '<b>8. Marrazoa: espekulatzailea. Gandiako glampinga.</b><br>Itsaso urdinaren sakontik marrazo isila agertzen da,<br>Gandia bankete baten antzera begiratzen du;<br>solar huts bat ikusten duen tokian<br>ordurako txekea buruan du,<br>eta herria bere koskaren aurrean dardarka dago.',
  'Batzuek piztia basati batekin nahasten dute,<br>baina arrisku benetakoa jantzi finez doa;<br>hitzarmenak sinatzen ditu eskuz oso "humanotan"<br>eta auzoa koral baino garestiago uzten du.',
  'Denborale baino gehiago irauten duten proiektuak,<br>etengabe itzultzen diren lehiaketak;<br>zenbat eta gehiago apaindu promesak,<br>orduan eta gehiago usaintzen dute boto‑usain.',
  'Glamping horrek postaleko paradisua agintzen du,<br>larruz bildutako ke berdea saltzen;<br>baina hemengo igelak eta hegaztiak zapaltzen ditu,<br>eta isiltasuna krimen ekologiko bihurtzen.',
  'Alkateak dio: "aurrerapen jasangarria da",<br>marrazoak notario aurrean sinatzen duen bitartean;<br>proiektua egina, etekina argi eta egunero,<br>eta hortza dardarka, ahul eta ia ikusezin.',
  'Fin igeri egiten dute, ezer gertatuko ez balitz bezala,<br>prezioa gure gain eroriko ez balitz bezala;<br>eta itsasoak xuxurlatzen jarraitzen du, sakon eta etengabe:<br>"okerrenak deklaratu gabe geratzen diren koskak dira".',
  '<b>9. Pardal pirata duen upela.</b><br>Lurra ukitu gabe altxatu nahi duen norbait bezala,<br>hor dugu hegazti txikia barrilaren gainean;<br>alkate neurtua da, hegaldia kontuzkoa,<br>hitz leun eta tonu barean mintzo dena.',
  'Oxidatutako barril isil horren gainean<br>oreka ariketa finak egiten ditu;<br>badaki behera jaisteak prezio handia duela,<br>eta goitik pisua arinagoa dirudi beti.',
  'Kontratuen itsaso honetan<br>patroi handiak nabigatu du:<br>Ábalos, idazkari betikoa,<br>antolaketa osoa eramaten zuena.',
  'Dio berak soilik egiten zuela ibilbidea<br>portu instituzionalaren artean;<br>baina itsasontzia geldialdi bereziak egiten zituen<br>kutxa berezia zegoen lekuetan.',
  'Ontzi osoan zehar Koldo dabil korrika,<br>oso karramarro azkarra;<br>poltsa eta maleta betetakoak igotzen<br>kaianetik erreserbatutako gelara.',
  'Cerdánek esaten du bidaia egiten duela<br>nazioari zerbitzua emateko;<br>baina bitartean sarea zabal‑zabal hedatzen du<br>komisio berriak arrantzatzeko.',
  'Baina herriak, itsasgizona baita,<br>kantu zahar hau ondo ezagutzen du:<br>hainbeste txistor eta zarata dagoenean…<br>norbaitek perola ordaindu behar du.',
  'Gobernatzea ez baita lokatzetik ihes egitea soilik,<br>ezta orain dagoen gatazkaren gainetik hegan egitea ere;<br>behera jaitsi, uneak duen pisua hartu<br>eta pozoiak azkenean hondoratu ez gaitzan saiatzea da.',
  'Eta horrela, barrila oraindik beterik dagoela,<br>pardalak norabidea eta jarrera mantentzen ditu;<br>baina itsasoak ahots helduago batekin xuxurlatzen du:<br>"ongi gobernatzea ere behera jaitsi eta egitea da".'
];

