export const criticaMajorEn = [
  '<b>CATAFALQUE SCENE. INTRODUCTION.</b><br>Between waves of empty words<br>rise ships of smoke and lies;<br>the people row, blind and tired,<br>searching for a shore that has never arrived.',
  'On the coast, the usual ones promise<br>"a Gandia better than yesterday",<br>but between photos and grand projects<br>everything returns to the same grey tone.',
  'Beneath the city, the sea no longer believes.<br>Triton raises his arm, calls up the wave,<br>but his shout fades away at dawn<br>and the sunken people say: "This is what we see".',
  'Triton denounces a harbour with no course,<br>full of decrees, manoeuvres and debris;<br>shadows that dance under the moon<br>and deals that weigh like lead on the seabed.',
  'The mermaid laughs beneath the water,<br>as if she already knew how it ends:<br>"You are already sunk, and still you want<br>more sea to sit and bargain again?"',
  'They say: "We have everything under control",<br>like when a storm hits Germanies;<br>but the water denies their story<br>and the sea sweeps away the fantasies.',
  'The sailor chases glory,<br>like one who promises change on every corner;<br>but the serpent tells him the story:<br>those who never work will never find the flower.',
  'In the end both pirates and their gold<br>are fables of a world already exhausted;<br>and Gandia, who knows the market well,<br>chooses her own harbour more wisely.',
  '<b>1. Captain of the Special Section Fallas.</b><br>The "captain" holds the helm,<br>sees the fiesta as a company;<br>every act a brand‑new piece<br>to make the cashbox overflow.',
  'The new "Florentino" has arrived,<br>from Vila Nova he commands;<br>he organises, adds and plots,<br>with a balance sheet carefully planned.',
  'Prado holds its position,<br>refuses to lose its category;<br>if the census figures do not add up,<br>they will fix them, saving the glory.',
  'Mártires wants to leave a mark,<br>they have thrown the house out the window;<br>a monument that devours it all<br>to win a place in the story.',
  'Mercat arrives as the new one,<br>wants a word with the children\'s falla;<br>and even if it looks more humble,<br>it makes itself heard with plenty of swagger.',
  'Vila Nova has become Port Nou,<br>as if it were the very same rank;<br>where there once was peace and calm,<br>now everything moves for the “sou” in the bank.',
  'The town hall happily nods<br>if Gandia gains more fame,<br>while the Board keeps complaining,<br>having long since lost its aim.',
  'And the captain sees it clearly:<br>that the fiesta is just a market;<br>everything signed and rubber‑stamped,<br>as he keeps on adding profit.',
  '<b>2. Barrel 1. Manipulated graduates.</b><br>In the sea that surrounds our monument<br>float barrels nobody will claim;<br>they carry poison, they carry drama,<br>and an endless chorus of "I\'m not to blame".',
  'In Gandia the poison has its soundtrack:<br>rumour, tension and interested voices;<br>heated talk shows, fractured truth,<br>and a quiet complicity that paints all the choices.',
  'Radio Gandia gives the headline,<br>Onda Naranja lights up the debate;<br>and while the poison slowly rises,<br>the airwaves speak from every gate:',
  'Comarcal TV paints a postcard,<br>Radio Marca stirs conversation;<br>a lot of noise, little way back,<br>and the depth grows darker in every station.',
  'Talk shows where three people speak and eight are shouting,<br>stations that twist the storyline;<br>depending on who gets on the set,<br>past sins are suddenly left behind.',
  'There are also "holy" jellyfish<br>floating across the information,<br>that sting with delicate little forms<br>when they repeat the same narration.',
  'If a lie is repeated<br>a thousand times along the band,<br>it ends up sounding like breaking news<br>no matter how trivial or bland.',
  'But the people, seasoned fishers,<br>already know this ocean well:<br>when the noise becomes too loud,<br>someone\'s trying to make you spin.',
  '<b>3. Barrel 2.</b><br>From Gandia on towards Valencia<br>sails a very curious boat;<br>they call it the commuter train,<br>but it is rarely there to board.',
  'One day it runs, the next it rests,<br>another it reaches the port too late;<br>and every passenger checks their watch<br>as half a morning slips away.',
  'Between breakdowns and long delays<br>the people now have a tradition:<br>to take provisions for the trip<br>and pray for the patron\'s protection.',
  'When the train fails yet again<br>nobody offers explanations;<br>the travellers packed like sardines<br>are squeezed tight in the wagons.',
  'Governments change and change again<br>without any serious objection,<br>yet not one of them truly sets to work<br>to finish the Mediterranean connection.',
  'The people, who are travellers,<br>already say with resignation:<br>if you want to get to Valencia…<br>leave home before dawn\'s first light.',
  '<b>4. Ecological – 50th anniversary ship.</b><br>Half a century fighting winds and tides,<br>turning every blow into a lesson that shapes us,<br>and every shipwreck into a new awakening,<br>with a stubborn flame that refuses to fall silent.',
  'Fifty winters standing firm in the storm,<br>shouting to the world that here the flame is fiesta,<br>and that persistence is the craft we inherited<br>from a falla that has never surrendered.',
  'Now we look back with calmer eyes,<br>knowing that our errors made us more skilled;<br>half a century of falling and planting again,<br>of sinking together… and rising together once more.',
  'And here we stand, proud, in calm seas,<br>staring at the future without any chains.<br>If history has steered us to sail like this,<br>let it be fifty more years… and may they be here.',
  '<b>5. Sirens – Opposition.</b><br>Like the sweetest of siren songs<br>so sings the opposition in Gandia;<br>they paint everything as pitch‑black night,<br>but never bring a real salida.',
  'To make their videos extra viral<br>the politicians stage their fight;<br>Soler, playing star reporter,<br>casts a Gandia drenched in drama.',
  'Millet with his coffee‑camera crew<br>looks like a parody straight from Vox;<br>but he does it fully conscious:<br>we will be in trouble if he gets the box.',
  'The PP goes about uncovering<br>all the city\'s hidden shames;<br>the “cheque consumo”, they say, is fraud,<br>data downloads done without a please.',
  'They claim the door was wide open<br>in the municipal census lists;<br>that lenient hands stretched far too wide<br>and the city suddenly grew immense.',
  'And while they criticise and criticise,<br>they already think of elections;<br>they smile at us with friendly faces<br>to scrape together our affections.',
  'It hardly matters which party they wear,<br>the only thing they want is to win.<br>But people now are sharper‑eyed:<br>we will not be fooled again.',
  'With Mazón already in the government<br>Soler and his gang will do quite little;<br>for here we won\'t forget the Dana storm<br>nor that Sánchez sent no help at all.',
  '<b>6. LGTBI.</b><br>To love is not a crime,<br>nor a reason to condemn;<br>homophobia, that is<br>the shame with no end.',
  'Equality never subtracts,<br>it only adds more hearts,<br>and the world will only be fair<br>when every love has its part.',
  'We are who we are<br>without asking for forgiveness;<br>with pride filling the streets,<br>with love free from fear.',
  'We do not ask for privileges<br>nor places above the rest;<br>just rights we all can share<br>and streets where we walk unpressed.',
  'The LGTBI+ movement<br>is neither fad nor nice décor;<br>it is the right to live in freedom<br>without hiding, without fear.',
  'No insult will ever put out<br>the light of a truthful love;<br>against homophobia we answer<br>with respect for every heart.',
  '<b>7. Scene of the castaway Francisco on the desert island.</b><br>Francisco, the great conqueror,<br>who came to modernise the show,<br>to redesign each official act,<br>is now grounded in the shoals.',
  'On his very own desert island<br>he finds little real support,<br>and his strength is slowly fading<br>to keep the whole machine in motion.',
  'So now good Mr. Francisco<br>has enthroned himself in Foc i Flama,<br>so that his voice might thunder loud<br>from the Grao to Benipeixcar.',
  'A Foc i Flama with two editions,<br>what an innovation bold;<br>choose whichever photo you prefer<br>for the next year\'s fold.',
  'A poor choice of new portraitist,<br>used to dealing with an artist;<br>he has thought that this whole volume<br>is a glossy little magazine.',
  'It will help Joaquín Lerma plenty<br>to pay for the broken bridge;<br>for this year\'s Foc i Flama,<br>everyone will surely reuse.',
  'Telmo has come out quite well,<br>better than the one before;<br>we will see what still remains,<br>for things could still get worse.',
  '<b>8. Shark: speculator. Gandia glamping.</b><br>From the deep blue emerges the silent shark,<br>he looks at Gandia as a banquet on the chart;<br>where he sees an empty plot of land<br>he already tastes the cheque in hand,<br>and the people tremble at his bite.',
  'Some confuse him with a wild beast,<br>but the real danger wears a suit;<br>he signs agreements with a very human hand<br>and leaves the neighbourhood dearer than coral.',
  'Projects that last longer than any storm,<br>tenders that return again and again;<br>promises that, the more they shine,<br>taste all the more of vote‑bait slime.',
  'The glamping sells a postcard paradise,<br>green‑washed smoke wrapped up in lard;<br>but it crushes frogs and local birds<br>and turns silence into an environmental crime.',
  '“It is sustainable progress”, says the mayor,<br>while the shark signs neatly before the notary;<br>the project ready, the profit clear and daily,<br>and the tooth is trembling, fragile and unseen.',
  'They swim smoothly, as if nothing happened,<br>as if the price would not come crashing down;<br>and the sea keeps murmuring, deep and constant:<br>“the worst bite is always the one not declared”.',
  '<b>9. Barrel with little pirate bird.</b><br>Like someone who wants to rise up<br>without soiling shoes in mud,<br>there we find our careful mayor<br>balancing on his heavy drum.',
  'On top of the rusty, silent barrel<br>he keeps his balance with measured care;<br>he knows that climbing down has a price,<br>and from above the weight seems light.',
  'In this sea that swirls with contracts<br>once sailed a very great skipper:<br>Ábalos, ever the secretary,<br>keeping all the organisation.',
  'He says he merely followed routes<br>through the harbour of institutions,<br>but the ship would always make a stop<br>where the cashbox was quite special.',
  'Across the deck scuttles Koldo,<br>a very quick‑witted crab,<br>carrying bags and loaded cases<br>from the dock up to the lounge.',
  'Cerdán says he makes the journey<br>only to serve the noble nation,<br>while he keeps on casting nets<br>looking for each new commission.',
  'But the people, who are sailors,<br>already know this old refrain:<br>when there\'s so much festive chatter…<br>someone ends up paying the pot.',
  'Because to govern is not just avoiding the mud,<br>nor flying above the present clash;<br>it is going down, taking on the weight<br>and stopping the poison from sinking us all.',
  'And so, on top of the barrel still filled,<br>the little bird holds course and pose;<br>but the sea keeps murmuring, in a wiser voice:<br>“to govern well is also to go down and do”.'
];

