export const criticaMajorEs = [
  '<b>ESCENA CATAFALCO. INTRODUCCIÓN.</b><br>Entre olas de palabra vacía<br>se alzan barcos de humo y mentira;<br>el pueblo rema, ciego y cansado,<br>buscando la orilla que nunca ha llegado.',
  'En la costa, los de siempre prometen<br>"una Gandia mejor que ayer",<br>pero entre fotos y proyectos<br>todo vuelve al mismo color gris.',
  'Bajo la ciudad, el mar ya no cree.<br>Tritón alza el brazo, convoca la ola,<br>pero su grito se apaga en el alba<br>y el pueblo hundido dice: "Esto es lo que se ve".',
  'Tritón denuncia un puerto sin rumbo,<br>lleno de decretos, maniobras y ruina;<br>sombras que bailan bajo la luna<br>y acuerdos que pesan como plomo en el fondo.',
  'La sirena ríe bajo el agua,<br>como quien ya sabe cómo acabará:<br>Hundidos estáis, y aún queréis<br>más mar para volver a negociar?',
  'Dicen: "Lo tenemos controlado",<br>como cuando llueve fuerte en Germanías;<br>pero el agua desmiente el relato<br>y el mar se lleva las fantasías.',
  'El marinero busca gloria,<br>como quien promete cambios en la esquina;<br>pero la serpiente le cuenta la historia:<br>quien no trabaja no encuentra flor.',
  'Al final, tanto pirata como oro<br>son fábulas de un mundo ya cansado;<br>y Gandia, que conoce el mercado,<br>sabe elegir mejor su propio puerto.',
  '<b>1. Capitán de las Fallas de especial.</b><br>El “capitán” lleva el timón,<br>ve la fiesta como empresa;<br>cada acto es nueva pieza,<br>para hacer caja al pantalón.',
  'El nuevo “Florentino” ha llegado,<br>desde Vila Nova manda;<br>organiza, suma y trama,<br>con balance bien calculado.',
  'Prado aguanta la posición,<br>no quiere perder categoría;<br>si el censo no cuadra, ya se arregla,<br>mientras salvan distinción.',
  'Mártires quiere dejar huella,<br>han tirado la casa por la ventana;<br>monumento que todo lo devora,<br>para hacer historia que gana.',
  'Mercat llega nuevo,<br>quiere hablar con la infantil,<br>y aunque parezca más humilde,<br>sabe hacerse oír muy bien.',
  'Vila Nova ya es Port Nou,<br>como si fuera el mismo grado;<br>donde antes había calma,<br>ahora todo se mueve por el “sou”.',
  'El ayuntamiento dice sí,<br>si Gandia gana más fama,<br>mientras la Junta se reclama,<br>perdiendo el rumbo desde aquí.',
  'Y el capitán lo ve muy claro:<br>que la fiesta es puro mercado,<br>todo firmado y visado,<br>mientras vuelve a sumar.',
  '<b>2. Tonel 1. Titulados manipulados.</b><br>Dentro del mar de nuestro monumento<br>flotan barriles que nadie reclama;<br>llevan veneno, llevan drama,<br>y un “yo no he sido” permanente.',
  'En Gandia el veneno tiene banda sonora:<br>rumor, crispación y voz interesada;<br>tertulia encendida, verdad fragmentada,<br>y silencio cómplice que todo lo decora.',
  'Radio Gandia da el titular,<br>Onda Naranja el debate radiante.<br>Y mientras, el veneno sube, lento y constante,<br>las ondas hablan desde su canal:',
  'Comarcal TV pinta postal,<br>Radio Marca enciende la conversación;<br>mucho ruido, poca marcha atrás,<br>y el fondo sigue más abismal.',
  'Tertulias donde tres hablan y ocho gritan,<br>emisoras que cambian el relato;<br>según quién entra, todo queda olvidado,<br>y los barriles, mientras, más peso adquieren.',
  'También hay medusas divinas<br>flotando por la información,<br>que pican con formas finas<br>cuando repiten la lección.',
  'Si una mentira se repite<br>mil veces por el canal,<br>acaba pareciendo noticia…<br>por muy banal que en verdad sea.',
  'Pero el pueblo, viejo pescador,<br>ya conoce bien este océano:<br>cuando el ruido es demasiado grande<br>alguien te está mareando.',
  '<b>3. Tonel 2.</b><br>De Gandia hacia Valencia<br>sale un barco singular,<br>dicen que es tren de cercanías<br>pero cuesta de encontrar.',
  'Un día sale, otro descansa,<br>otro llega tarde al puerto,<br>y el pasajero mira el reloj<br>mientras pierde medio día muerto.',
  'Entre averías y retrasos<br>la gente ya tiene tradición:<br>llevar avituallamiento<br>y encomendarse al patrón.',
  'Cuando el tren vuelve a fallar<br>nadie ofrece explicaciones;<br>los viajeros cual sardinas<br>se aplastan en los vagones.',
  'Cambian gobiernos y colores<br>y sin apenas oposición<br>ninguno se pone en serio<br>a acabar el corredor mediterráneo.',
  'El pueblo, que es viajero,<br>ya dice con resignación:<br>si quieres llegar a Valencia…<br>sal de casa antes del sol.',
  '<b>4. Ecológica – Barco 50 aniversario.</b><br>Medio siglo luchando contra vientos y mareas,<br>haciendo de cada golpe una lección que nos crea,<br>y de cada naufragio un nuevo despertar,<br>con una llama tozuda que nunca quiere callar.',
  'Cincuenta inviernos plantando cara a la tormenta,<br>gritando al mundo que aquí la llama es la fiesta,<br>y que persistir es el oficio heredado<br>de una falla que jamás se ha rendido.',
  'Ahora miramos atrás con ojos tranquilos,<br>sabiendo que los errores nos hicieron más hábiles;<br>medio siglo de caer y volver a plantar,<br>de hundirnos juntos... y juntos volver a alzar.',
  'Y aquí estamos, orgullosos, en mar serena,<br>mirando el futuro sin ninguna cadena.<br>Si la historia nos ha hecho navegar así,<br>cincuenta años más… y que sea aquí.',
  '<b>5. Sirenas – Oposición.</b><br>Como cantan las bellas sirenas<br>canta en Gandia la oposición.<br>Todo lo ven negro y oscuro,<br>pero no traen solución.',
  'Para que el vídeo sea más viral<br>la batalla en redes se dan;<br>Soler, como si fuera reportero de fama,<br>pinta una Gandia llena de drama.',
  'Millet y su cámara café<br>parecen Vox en parodia;<br>pero lo hace muy consciente:<br>negro lo tendremos si gobierna.',
  'El PP va sacando vergüenzas.<br>El cheque consumo, dice, es un fraude,<br>con descarga masiva de datos<br>sin pedir ni un simple “por favor”.',
  'Dicen que abierta la puerta estaba<br>en el padrón municipal.<br>Que ha sido la manga ancha<br>y la ciudad se ha hecho muy grande.',
  'Y mientras critican y critican<br>ya piensan solo en elecciones.<br>Buena cara nos ponen ahora<br>para rascarnos los votillos.',
  'Da igual de qué partido sean,<br>lo único que quieren es ganar.<br>Pero el pueblo ya afina la vista:<br>ya no nos pueden engañar.',
  'Con Mazón dentro aún<br>poco harán Soler y cuadrilla;<br>que aquí no olvidamos la Dana<br>ni que Sánchez no mandó ayuda.',
  '<b>6. LGTBI.</b><br>Amar no es delito<br>ni motivo de condena,<br>la homofobia sí que es<br>la vergüenza eterna.',
  'La igualdad no resta,<br>suma corazones,<br>y el mundo será más justo<br>cuando respetemos todos los amores.',
  'Somos quienes somos<br>sin pedir perdón;<br>orgullo en la calle,<br>amor sin temor.',
  'No pedimos privilegios<br>ni lugares superiores,<br>sino derechos compartidos<br>y calles sin temores.',
  'El movimiento LGTBI+<br>no es moda ni reclamo,<br>es derecho a vivir en libertad<br>sin miedo y sin escondernos.',
  'Ningún insulto apagará la luz<br>de un amor sincero;<br>contra la homofobia<br>respeto para querer.',
  '<b>7. Escena del náufrago Francisco en la isla desierta.</b><br>Francisco el conquistador<br>que venía a modernizar<br>y los actos remodelar<br>ya se ha quedado encallado.',
  'En su isla desierta<br>se encuentra poco apoyado<br>y ya flaquean las fuerzas<br>para sacarlo todo adelante.',
  'Por eso el señor Francisco<br>en Foc i Flama se ha entronizado<br>para que su voz retumbe<br>del Grao hasta Benipeixcar.',
  'Un Foc i Flama con dos versiones,<br>toda una innovación;<br>elige la foto que quieras<br>para la siguiente edición.',
  'Mal cambio de retratista,<br>acostumbrado al artista;<br>ha pensado que este libro<br>era solo otra revista.',
  'Bien le vendrá a Joaquín Lerma<br>para pagar la rotura del puente,<br>ya que el Foc i Flama este año<br>lo reciclará toda la gente.',
  'A Telmo le ha salido bien,<br>mejor que al anterior;<br>ya veremos qué queda en pie,<br>que aún puede ser peor.',
  '<b>8. Tiburón: especulador. Glamping de Gandia.</b><br>Del azul profundo emerge el tiburón sigiloso,<br>mira Gandia como quien mira un banquete;<br>donde ve un solar ya imagina el cheque,<br>y el pueblo tiembla ante su mordisco.',
  'Algunos lo toman por fiera animal,<br>pero el peligro real lleva americana;<br>firma convenios con mano muy humana<br>y deja el barrio más caro que el coral.',
  'Proyectos que duran más que un temporal,<br>licitaciones que vuelven y vuelven;<br>promesas que, cuanto más se adornan,<br>más saben a escama electoral.',
  'El glamping promete un paraíso postal,<br>vende humo verde envuelto en grasa,<br>pero aplasta ranas y aves de aquí,<br>y hace del silencio un crimen ambiental.',
  'Dice el alcalde: “es progreso sostenible”,<br>mientras el tiburón firma ante notario,<br>lleva el negocio hecho, el beneficio claro y diario,<br>y el colmillo tiembla, frágil e invisible.',
  'Nadan finos, como si nada pasara,<br>como si el precio no cayera encima;<br>y el mar murmura, constante y profundo:<br>“el peor mordisco es el que no se declara”.',
  '<b>9. Barril con pardillo pirata.</b><br>Como quien quiere elevarse sin pisar el barro,<br>ahí tenemos al alcalde de vuelo mesurado;<br>habla fino, tranquilo, muy moderado,<br>mientras el barril sigue lleno y pesado.',
  'Sobre el bidón oxidado y callado<br>hace equilibrios con prudencia y tino;<br>sabe que bajar tiene un coste elevado,<br>y arriba el peso siempre parece más fino.',
  'En este mar de contratos<br>navegaba un gran patrón:<br>Ábalos, siempre secretario,<br>llevando toda la organización.',
  'Dice que él solo hacía ruta<br>por el puerto institucional,<br>pero el barco hacía escala<br>donde la caja era especial.',
  'Por el barco corre Koldo,<br>cangrejo muy espabilado,<br>subiendo bolsas y maletines<br>del muelle al reservado.',
  'Cerdán dice que hace el viaje<br>para servir a la nación,<br>mientras va tendiendo la red<br>para pescar cada comisión.',
  'Pero el pueblo, que es marinero,<br>ya conoce bien la canción:<br>cuando hay tanta charanga y cuento…<br>alguien paga el perolón.',
  'Porque gobernar no es solo evitar el fango,<br>ni volar por encima del conflicto presente;<br>es bajar, asumir el peso del momento,<br>y evitar que el veneno nos acabe hundiendo.',
  'Y así, encima del barril aún lleno,<br>el pardillo mantiene rumbo y postura;<br>pero el mar murmura con voz madura:<br>“gobernar bien también es bajar y hacer”.'
];
