export const criticaMajorEs = [
  'Entre olas de palabra vacía<br>se alzan barcos de humo y mentira;<br>el pueblo rema, ciego y cansado,<br>buscando la orilla que nunca ha llegado.',
  'En la costa, los de siempre prometen<br>"una Gandia mejor que ayer",<br>pero entre fotos y proyectos<br>todo vuelve al mismo color gris.',
  'Bajo la ciudad, el mar ya no cree.<br>Tritón alza el brazo, convoca la ola,<br>pero su grito se apaga en el alba<br>y el pueblo hundido dice: "Esto es lo que se ve".',
  'Tritón denuncia un puerto sin rumbo,<br>lleno de decretos, maniobras y ruina;<br>sombras que bailan bajo la luna<br>y acuerdos que pesan como plomo en el fondo.',
  'La sirena ríe bajo el agua,<br>como quien ya sabe cómo acabará:<br>Hundidos estáis, y aún queréis<br>más mar para volver a negociar?',
  'Dicen: "Lo tenemos controlado",<br>como cuando llueve fuerte en Germanías;<br>pero el agua desmiente el relato<br>y el mar se lleva las fantasías.',
  'El marino busca gloria,<br>como quien promete cambios al canto;<br>pero la serpiente le cuenta la historia:<br>quien no trabaja no encuentra flor.',
  'Al final, tanto pirata como oro<br>son fábulas de un mundo ya cansado;<br>y Gandia, que conoce el mercado,<br>sabe elegir mejor su propio puerto.',
  '<b>Escena 1. Capitán de barco</b><br>Capitán de las Fallas de especial.<br>El "capitán" lleva el timón,<br>ve la fiesta como empresa;<br>cada acto es nueva pieza,<br>para hacer caja al pantalón.',
  'El nuevo "Florentino" ha llegado,<br>desde Vila Nova manda;<br>organiza, suma y trama,<br>con balance bien calculado.',
  'Prado aguanta la posición,<br>no quiere perder categoría;<br>si el censo no cuadra, ya se arregla,<br>mientras salvan distinción.',
  'Mártirs quiere dejar huella,<br>han tirado la casa por la ventana;<br>monumento que todo lo devora,<br>para hacer historia que venza.',
  'Mercat llega nuevo,<br>quiere hablar con la infantil,<br>y aunque sea humilde,<br>sabe hacerse sentir bastante.',
  'Vila Nova ya es Port Nou,<br>como si fuera el mismo grado;<br>donde antes había paz,<br>ahora todo se mueve por el "sou".',
  'El ayuntamiento dice sí,<br>si Gandia gana fama,<br>mientras la Junta se reclama,<br>perdiendo rumbo desde aquí.',
  'Y el capitán ve claro,<br>que la fiesta es mercado,<br>todo firmado y visado,<br>mientras vuelve a sumar.',
  '<b>Escena 2. Tonel 1</b><br>Escena del náufrago Francisco en la isla desierta.<br>Francisco el conquistador<br>que venía a modernizar<br>y los actos remodelar<br>ya se ha quedado encallado.',
  'En su isla desierta<br>se encuentra poco apoyado<br>y ya flaquean las fuerzas<br>para llevarlo todo adelante.',
  'Por eso el sr. Francisco<br>en Foc i Flama se ha entronizado<br>que su voz retumba<br>del Grao a Benipeixcar.',
  'Un Foc i Flama con dos versiones<br>todo una innovación<br>elige la foto que quieras<br>para la siguiente edición.',
  'Mal cambio de retratista<br>acostumbrado al artista<br>se ha pensado que este libro<br>es como una revista.',
  'Bien le vendrá a Joaquín Lerma<br>para pagar la rotura del puente<br>ya que el Foc i Flama este año<br>lo reciclará todo el mundo.',
  'A Telmo le ha venido bien<br>y mejor que al anterior<br>veremos lo que queda<br>que aún puede ser peor.',
  '<b>Escena 3. Tonel 2</b><br>Tiburón: especulador. Glamping de Gandia.<br>Del azul profundo sale el tiburón sigiloso,<br>mira Gandia como quien mira un banquete;<br>donde ve un solar ya imagina el cheque,<br>y el pueblo tiembla ante su mordisco.',
  'Algunos lo confunden con fiera animal,<br>pero el peligro real lleva americana;<br>firma convenios con mano muy humana<br>y deja el barrio más caro que el coral.',
  'Proyectos que duran más que un temporal,<br>licitaciones que vuelven y vuelven;<br>promesas que, cuando más se adornan,<br>saben a escama electoral.',
  'El glamping promete un paraíso postal,<br>vende humo verde envuelto en savia,<br>pero aplasta ranas y aves de aquí,<br>y hace del silencio un crimen ambiental.',
  'Dice el alcalde: "es progreso sostenible",<br>mientras el tiburón ya firma ante notario,<br>lleva el proyecto hecho, el beneficio claro y diario,<br>y el colmillo tiembla, frágil e invisible.',
  'Nadan bien, como si nada pasara,<br>como si el precio no cayera encima;<br>y el mar murmura, constante y profundo:<br>"el peor mordisco es el que no se declara".',
  '<b>Escena 4. Ecológica</b><br>Tonel 1. Titulados manipulados.<br>Dentro del mar de nuestro monumento<br>flotan barriles que nadie reclama;<br>llevan veneno, llevan drama,<br>y un "yo no he sido" permanente.',
  'En Gandia el veneno tiene banda sonora:<br>rumor, crispación y voz interesada;<br>tertulia encendida, verdad fragmentada,<br>y silencio cómplice que todo lo decora.',
  'Radio Gandia da el titular,<br>Onda Naranja el debate radiante.<br>Y mientras, el veneno sube, lento y constante,<br>las ondas hablan desde su canal:',
  'Comarcal TV pinta postal,<br>Radio Marca enciende la conversación;<br>mucho ruido, poca reversa,<br>y el fondo sigue más abismal.',
  'Tertulias donde tres hablan y ocho gritan,<br>emisoras que cambian el relato;<br>según quién entra, todo queda olvidado,<br>y los barriles, mientras, más peso adquieren.',
  'También hay medusas divinas<br>flotando por la información,<br>que pican con formas finas<br>cuando repiten la lección.',
  'Si una mentira se repite<br>mil veces por el canal,<br>acaba pareciendo noticia…<br>por mucho que sea banal.',
  'Pero el pueblo, viejo pescador,<br>ya conoce bien este océano:<br>cuando el ruido es demasiado grande<br>alguien te está mareando.',
  '<b>Escena 5. Las Sirenas</b><br>Tonel 2. De Gandia hacia Valencia.<br>Sale un barco muy singular,<br>dicen que es tren de cercanías<br>pero cuesta de encontrar.',
  'Un día sale, otro descansa,<br>otro llega tarde al puerto,<br>y el pasajero mira el reloj<br>mientras pierde media mañana muerta.',
  'Entre averías y retrasos<br>la gente ya tiene tradición:<br>llevar avituallamiento<br>y encomendarse al patrón.',
  'Cuando el tren vuelve a fallar<br>nadie da explicaciones<br>los pasajeros como sardinas<br>se aprietan en los vagones.',
  'Cambian los gobiernos<br>y sin ningún importuno<br>ninguno se pone a acabar<br>el corredor mediterráneo.',
  'El pueblo, que es viajero,<br>ya dice con resignación:<br>si quieres llegar a Valencia…<br>sal de casa antes del sol.',
  '<b>Escena 6. Escena LGTBI</b><br>Barril con pardillo pirata.<br>Como quien quiere elevarse sin tocar fango,<br>ahí tenemos al alcalde de vol mesurado;<br>habla fino, con tono calmado y moderado,<br>mientras el barril sigue lleno y pesado.',
  'Encima del bidón oxidado y callado,<br>hace equilibrios con prudencia y tino;<br>sabe que bajar tiene un precio elevado,<br>y arriba el peso siempre parece aliviado.',
  'En este mar de contratos<br>navegaba un gran patrón:<br>Ábalos el secretario<br>llevando la organización.',
  'Dice que él solo hacía ruta<br>por el puerto institucional,<br>pero el barco hacía escala<br>donde la caja era especial.',
  'Por el barco corre Koldo<br>un cangrejo muy espabilado,<br>subiendo bolsas y maletines<br>del muelle hasta el reservado.',
  'Cerdán dice que hace el viaje<br>para servir a la nación,<br>mientras va tendiendo la red<br>para pescar comisiones.',
  'Pero el pueblo, que es marino,<br>ya conoce bien la canción:<br>cuando hay tanta algarabía…<br>alguien paga el pato.',
  'Porque gobernar no es solo evitar el fango,<br>ni volar encima del conflicto presente;<br>es bajar, asumir el peso del momento,<br>y evitar que el veneno nos acabe hundiendo.',
  'Y así, encima del barril aún lleno,<br>el pardillo mantiene el rumbo y la postura;<br>pero el mar murmura con voz madura:<br>"Gobernar bien también es bajar y hacer".',
  '<b>Escena 7. Naufragio</b><br>Ecológica – Barco 50 aniversario.<br>Medio siglo luchando contra vientos y mareas,<br>haciendo de cada golpe una lección que nos crea,<br>y de cada naufragio un nuevo despertar,<br>con una flama tozuda que nunca quiere callar.',
  'Cincuenta inviernos haciendo fuerza en la tempestad,<br>gritando al mundo que aquí la flama es hacer fiesta,<br>y que persistir es el oficio heredado,<br>de una falla que no se ha rendido jamás.',
  'Ahora miramos atrás con ojos tranquilos,<br>sabiendo que los errores nos hicieron más hábiles;<br>medio siglo de caer y volver a plantar,<br>de hundirnos juntos... y juntos volver a levantar.',
  'Y aquí estamos, orgullosos, en mar serena,<br>mirando el futuro sin ninguna cadena.<br>Si la historia nos ha hecho navegar así,<br>cincuenta años más... y que sea aquí.',
  '<b>Escena 8. Tiburón</b><br>LGTBI.<br>Amar no es un delito<br>ni motivo de condena,<br>la homofobia sí que es<br>la vergüenza eterna.',
  'La igualdad no resta,<br>suma corazones<br>y el mundo será justo<br>cuando respetemos todos los amores.',
  'Somos quienes somos<br>sin pedir perdón<br>orgullo en la calle<br>amor sin miedo.',
  'No pedimos privilegios<br>ni lugares superiores<br>solo derechos compartidos<br>y calles sin miedo.',
  'El movimiento LGTBI+<br>no es moda ni reclamo<br>es un derecho a vivir libre<br>sin miedo ni esconderse.',
  'Ningún insulto apagará la luz<br>de un amor sincero,<br>contra la homofobia<br>respeto para querer.',
  '<b>Escena 9. Pardillo sobre tonel</b><br>Sirenas. Oposición.<br>Cómo cantan las bellas sirenas<br>canta en Gandia la oposición.<br>Todo lo ven bien negro,<br>pero no proponen solución.',
  'Para hacer el vídeo más viral<br>la batalla se la hacen los políticos.<br>Soler como si fuera reportero de fama,<br>crea una Gandia, toda llena de drama.',
  'Millet y su cámara café,<br>parece Vox una parodia.<br>Pero lo hace con conciencia<br>negro lo tendremos si gobierna.',
  'El PP va destapando las vergüenzas.<br>El cheque consumo, dice, es un fraude<br>con descarga de datos<br>sin pedir por favor.',
  'Dicen que abierta la puerta estaba<br>en el padrón municipal.<br>Que ha sido la manga ancha<br>y la ciudad se ha hecho bien grande.',
  'Y mientras critican y critican<br>piensan ya en elecciones.<br>Buena cara nos meten,<br>para arramplarnos los votos.',
  'Pero tanto da el partido<br>lo único que quieren es ganar.<br>Pero la gente ya ahora hilamos fino<br>ya no nos pueden engañar.',
  'Con Mazón dentro aún<br>poco harán Soler y cuadrilla.<br>Que aquí no olvidemos a la Dana<br>ni que Sánchez no envió ayuda.'
];
